app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id)) 

class User(UserMixin,db.Model):
    
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    pitches = db.relationship('Pitch',backref='user',lazy='dynamic')
    comments = db.relationship('Comment',backref='user',lazy='dynamic')
    @property
    def password(self):
        raise AttributeError('You cannot read the password attritube')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_content = db.Column(db.String())
    pitch_category = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls,id):
        pitches = Pitch.query.filter_by(id=id).all()
        return pitches
    @classmethod
    def get_all_pitches(cls):
        pitches = Pitch.query.order_by('id').all()
        return pitches
    
    @classmethod
    def get_category(cls,cat):
        category = Pitch.query.filter_by(pitch_category=cat).order_by('id').all()
        return category

class Comment(db.Model):
    __tablename__='comments'

    id = db.Column(db.Integer,primary_key=True)
    comment_content = db.Column(db.String())
    pitch_id = db.Column(db.Integer)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(pitch_id=id).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    pitch = TextAreaField('Write Your Pitch',validators=[Required()])
    pitch_category = SelectField('Pitch Category',choices=[('Technology-Pitch','Technology Pitch'),('Business-Pitch','Business Pitch'),('Interview-Pitch','Interview Pitch'),('Pickup-Line','Pickup-Line Pitch'),('Promotion-Pitch','Promotion Pitch')],validators=[Required()])
    submit = SubmitField('Submit Pitch')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment about the above Pitch', validators=[Required()])
    submit = SubmitField('Submit Comment')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

#Initialize Flask Extensions
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)

    # Create app configurations
    app.config.from_object(config_options[config_name])

    #Initialize flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Register BluePrint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Register auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors,forms

app/main/views.py
from flask import render_template,redirect,url_for,request,abort,flash
from . import main
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchForm,CommentForm
from flask_login import login_required,current_user
from .. import db,photos

@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    return render_template('index.html')


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/pitches', methods = ['GET', 'POST'])
@login_required
def pitches_list():
    pitch_form = PitchForm()
    
    if pitch_form.validate_on_submit():
        pitch = pitch_form.pitch.data
        cat = pitch_form.pitch_category.data

        new_pitch = Pitch(pitch_content=pitch, pitch_category = cat, user = current_user)
        new_pitch.save_pitch()

        return redirect(url_for('main.pitches_list'))

    all_pitches = Pitch.get_all_pitches()

    title = 'Pitches Page'    
    return render_template('pitches.html', title = title, pitch_form = pitch_form, pitches = all_pitches)

@main.route('/comments/<int:id>',methods = ['GET','POST'])
@login_required
def pitch(id):
    
    my_pitch = Pitch.query.get(id)
    comment_form = CommentForm()

    if id is None:
        abort(404)

    if comment_form.validate_on_submit():
        comment_data = comment_form.comment.data
        new_comment = Comment(comment_content = comment_data, pitch_id = id, user = current_user)
        new_comment.save_comment()

        return redirect(url_for('main.pitch',id=id))

    all_comments = Comment.get_comments(id)


    title = 'Comments Page'
    return render_template('comments.html',pitch = my_pitch, comment_form = comment_form, comments = all_comments, title = title)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navigation Bar -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!-- Styling -->
{% block styles %}
    {{ super()}}
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Righteous" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
                <h4>Pitch Author: <strong><em>{{pitch.user.username|capitalize}}</em></strong></h4><hr>
                <p class="content">{{pitch.pitch_content}}</p><hr>
                <div class="row">
                    <div class="col-md-12">
                        {{wtf.quick_form(comment_form)}}
                        {{macro.displayComments(comments)}}
                    </div>
                </div>
                
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock%}

app/templates/fourOwfour.html
{%extends 'base.html'%}
{%block content%}
<div id="notfound">
    <div class="notfound">
        <div class="notfound-404">
            <div></div>
            <h1>404</h1>
        </div>
        <h2>Page not found</h2>
        <p>The page you are looking for might have been removed or had its name changed or is temporarily unavailable.</p>
        <a href="{{ url_for('main.index')}}">Home Page</a>
    </div>
</div>
{% endblock %}

app/templates/four_Ow_four.html
{%extends 'base.html'%}
{%block content%}
<div id="notfound">
    <div class="notfound">
        <div class="notfound-404">
            <div></div>
            <h1>404</h1>
        </div>
        <h2>Page not found</h2>
        <p>The page you are looking for might have been removed or had its name changed or is temporarily unavailable.</p>
        <a href="{{ url_for('main.index')}}">Home Page</a>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}


{% block content%}
<html>
    <body class="home" style="background:url( {{url_for('static',filename='photos/books.jpg') }})">
    <div class="container-fluid ">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center" style = "color: rgb(255, 255, 255)">Welcome to Pitch an Idea</h1><br>
                <h2 class="text-center" style="color: rgb(255, 255, 255)">To Great Ideas</h2>
                <h2 class="text-center" style = "color:rgb(255, 255, 255)"> Create an Account to Pitch your Ideas </h2>     
            </div>
        </div>
    </div>  
    </body>
</html>

{% endblock%}

app/templates/macros.html
{% macro displayPitches(pitches) %}
{% for pitch in pitches %}
<div class="col-md-12 pitch_list">
    {% if pitch.user.profile_pic_path %}
    <p>
            <img src="{{url_for('static',filename = pitch.user.profile_pic_path)}}" alt="" class="img-thumbnail">
            <h5>Username:<strong>{{pitch.user.username|capitalize}}</strong></h5>
    </p>
    {% else %}
    <p>
            <img src="{{url_for('static',filename = 'photos/Avatar.png')}}" alt="" class="img-thumbnail">
            <h5>Username: <strong>{{pitch.user.username|capitalize}}</strong></h5>
    </p>    
    {% endif %}
    <h5>{{pitch.pitch_content}}</h5>
    <h5><strong>Category: </strong>{{pitch.pitch_category}}</h5>
    <p class="btn btn-success comment"><a href="/comments/{{pitch.id}}">Comments</a></p>
</div>
{% endfor %}
{% endmacro %}

{% macro displayComments(comments_list)%}
{% for comment in comments_list%}
<div class="container-fluid">
<div class="card style-card">
        <div class="card-header ">
          <h4>Pitch Comments</h4> 
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>{{comment.comment_content}}</p>
            <footer class="blockquote-footer cmm">Comments By <cite title="Source Title"><strong>{{comment.user.username|capitalize}}</strong></cite></footer>
          </blockquote>
        </div>
</div>
</div>    
{% endfor%}
{% endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Pitch </a>
            
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{url_for('main.pitches_list')}}">View Pitches</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.register')}}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                <li><a href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>

        </div>
        
    </div>
</div>

app/templates/pitches.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    {{wtf.quick_form(pitch_form)}}
                </div>
                {{macro.displayPitches(pitches)}}
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-5 profile_pic">
        <!-- Prof Pic -->
        {% if user.profile_pic_path %}
        <p class="user-tag"> <strong>Username: </strong>{{user.username|capitalize}} </p>
        <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
        {% else %}
        <img src="{{url_for('static',filename = 'photos/Avatar.png')}}" alt="" class="img-thumbnail">
        {% endif %}
        
        {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
            <input type="file" name="photo" class="form-control" required>
            <input type="submit">
        </form>
        {% endif %}
    </div>
    <div class="col-md-7">
        <h4>Bio Information</h4>
        {% if user.bio %}
            <p> {{user.bio}} </p>
        {% else %}
        <p>{{user.username}} has no bio</p>
        {% endif %}
        {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a><br>
        {% endif %}
    </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {{wtf.quick_form(form)}}
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
{% endblock %}